language: ruby
rvm:
 - 2.1

script:
 - bundle exec jekyll build
 - bundle exec htmlproof ./_site --only-4xx --check-html

branches:
  only:
  - gh-pages
  - /pages-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true