title: 'Randson'
email: 'orandson@gmail.com'
description: ''
sub_name: ''

# configurations
timezone: America/Curitiba

base_uri: '/'
base_url: 'http://rands0n.com'
name: 'rands0n.com'
url: 'http://rands0n.com'

excerpt_separator: '<!--more-->'

# exclude folders for ci
exclude: [vendor]

# permalink
permalink: :title/

sass:
  dir: _sass
  style: compressed

# Build settings
markdown: kramdown
